# Generated by Django 6.1.1 on 2026-10-01 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Savol tartibi (#1, #2...)')),
                ('text', models.CharField(max_length=500, verbose_name='Savol matni')),
                ('explanation', models.TextField(blank=True, verbose_name="To'g'ri javob izohi")),
                ('points', models.PositiveIntegerField(default=10, verbose_name='Beriladigan ball')),
            ],
            options={
                'verbose_name': 'Savol',
                'verbose_name_plural': 'Savollar',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AnswerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Tartibi')),
                ('text', models.CharField(max_length=300, verbose_name='Variant matni (masalan: A) UTF-8)')),
                ('is_correct', models.BooleanField(default=False, verbose_name="To'g'ri variantmi")),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='quizzes.question', verbose_name='Savol')),
            ],
            options={
                'verbose_name': 'Javob varianti',
                'verbose_name_plural': 'Javob variantlari',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Mini-test sarlavhasi')),
                ('description', models.TextField(blank=True, verbose_name='Qisqa izoh')),
                ('pass_percentage', models.PositiveIntegerField(default=60, verbose_name="O'tish foizi (%)")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='courses.topic', verbose_name='Mavzu')),
            ],
            options={
                'verbose_name': 'Mini-test',
                'verbose_name_plural': 'Mini-testlar',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quizzes.quiz', verbose_name='Test'),
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveIntegerField(default=1, verbose_name='Urinish tartibi')),
                ('total_questions', models.PositiveIntegerField(default=0, verbose_name='Jami savollar')),
                ('correct_answers', models.PositiveIntegerField(default=0, verbose_name="To'g'ri javoblar")),
                ('score_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name="To'plangan foiz")),
                ('points_earned', models.PositiveIntegerField(default=0, verbose_name="Qo'lga kiritilgan ball")),
                ('passed', models.BooleanField(default=False, verbose_name="O'tdimi")),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='Yechilgan sana')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='quizzes.quiz', verbose_name='Test')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL, verbose_name="O'quvchi")),
            ],
            options={
                'verbose_name': 'Test topshirish natijasi',
                'verbose_name_plural': 'Test topshirish natijalari',
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentQuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quizzes.quizattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.question')),
                ('selected_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.answeroption')),
            ],
            options={
                'verbose_name': "O'quvchi savol javobi",
                'verbose_name_plural': "O'quvchi savol javoblari",
            },
        ),
    ]
