# Generated by Django 6.1.1 on 2026-10-01 10:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('first_name', models.CharField(max_length=150, verbose_name='Ism')),
                ('last_name', models.CharField(max_length=150, verbose_name='Familiya')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon raqam')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrator'), ('TEACHER', "O'qituvchi / Mentor"), ('STUDENT', "O'quvchi / Bilimdon"), ('PARENT', 'Ota-ona')], default='STUDENT', max_length=20, verbose_name='Rol')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Profil rasmi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': 'Foydalanuvchilar',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Guruh nomi (masalan: F-2401)')),
                ('description', models.TextField(blank=True, verbose_name='Guruh haqida tavsif')),
                ('telegram_group_url', models.URLField(blank=True, null=True, verbose_name='Telegram guruhi havolasi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ochilgan vaqti')),
                ('teacher', models.ForeignKey(blank=True, limit_choices_to={'role': 'TEACHER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentored_groups', to=settings.AUTH_USER_MODEL, verbose_name="Mentor / O'qituvchi")),
            ],
            options={
                'verbose_name': "O'quv guruhi",
                'verbose_name_plural': "O'quv guruhlari",
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ParentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_chat_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='Telegram Chat ID (bildirishnomalar uchun)')),
                ('receive_notifications', models.BooleanField(default=True, verbose_name='Bildirishnomalarni qabul qilish')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_profile', to=settings.AUTH_USER_MODEL, verbose_name='Ota-ona foydalanuvchisi')),
            ],
            options={
                'verbose_name': 'Ota-ona profili',
                'verbose_name_plural': 'Ota-onalar profillari',
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.PositiveIntegerField(default=0, verbose_name="Umumiy to'plangan ballar")),
                ('completed_tasks_count', models.PositiveIntegerField(default=0, verbose_name='Muvaffaqiyatli topshirilgan vazifalar')),
                ('passed_quizzes_count', models.PositiveIntegerField(default=0, verbose_name='Yechilgan testlar soni')),
                ('attendance_rate', models.DecimalField(decimal_places=2, default=100.0, max_digits=5, verbose_name="Davomat ko'rsatkichi (%)")),
                ('bio', models.TextField(blank=True, verbose_name="O'quvchi haqida qisqacha")),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='accounts.group', verbose_name='Guruh')),
                ('parent', models.ForeignKey(blank=True, limit_choices_to={'role': 'PARENT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to=settings.AUTH_USER_MODEL, verbose_name='Biriktirilgan Ota-ona')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name="O'quvchi foydalanuvchisi")),
            ],
            options={
                'verbose_name': "O'quvchi profili",
                'verbose_name_plural': "O'quvchilar profillari",
            },
        ),
    ]
