# Generated by Django 6.1.1 on 2026-10-01 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Kurs nomi')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Kurs tavsifi')),
                ('icon', models.CharField(default='code', max_length=50, verbose_name='Icon nomi (masalan: code, database, mobile)')),
                ('technologies', models.JSONField(blank=True, default=list, verbose_name="O'rgatiladigan texnologiyalar (masalan: ['HTML', 'CSS', 'JavaScript', 'React'])")),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
                ('is_active', models.BooleanField(default=True, verbose_name='Tizimda faolmi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kurs',
                'verbose_name_plural': 'Kurslar',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Modul nomi (masalan: HTML Asoslari)')),
                ('description', models.TextField(blank=True, verbose_name='Modul tavsifi')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Tartibi')),
                ('lessons_count_display', models.PositiveIntegerField(default=12, verbose_name="Darslar soni (ko'rinishi)")),
                ('topics_count_display', models.PositiveIntegerField(default=24, verbose_name="Mavzular soni (ko'rinishi)")),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.course', verbose_name='Qaysi kursga tegishli')),
            ],
            options={
                'verbose_name': 'Kurs Moduli',
                'verbose_name_plural': 'Kurs Modullari',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Mavzu nomi (masalan: Metateglar va Semantika)')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Mavzu tartib raqami')),
                ('lessons_count', models.PositiveIntegerField(default=4, verbose_name='Darslar soni')),
                ('duration_hours', models.DecimalField(decimal_places=1, default=1.5, max_digits=4, verbose_name='Davomiyligi (soat)')),
                ('description', models.TextField(blank=True, verbose_name='Mavzu matni / konspekt')),
                ('presentation_title', models.CharField(blank=True, max_length=255, verbose_name='Dars Prezentatsiyasi sarlavhasi (masalan: Metateglar va SEO asoslari)')),
                ('presentation_file', models.FileField(blank=True, null=True, upload_to='presentations/', verbose_name='Taqdimot fayli (.pdf)')),
                ('slides_count', models.PositiveIntegerField(default=18, verbose_name='Jami slaydlar soni')),
                ('source_code_url', models.URLField(blank=True, null=True, verbose_name='Kod havolasi (GitHub)')),
                ('source_code_snippet', models.TextField(blank=True, verbose_name='Namunaviy kod matni')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='Video tushuntirish havolasi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='courses.module', verbose_name='Modul')),
            ],
            options={
                'verbose_name': 'Mavzu (Darslik)',
                'verbose_name_plural': 'Mavzular (Darsliklar)',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OPEN', 'Ochiq'), ('WAITING', 'Yopiq (Navbat kutilmoqda)'), ('COMPLETED', 'Yakunlangan')], default='WAITING', max_length=20, verbose_name='Holati')),
                ('progress_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Kurs taraqqiyoti (%)')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='Yozilgan sana')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tugatilgan sana')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course', verbose_name='Kurs')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_enrollments', to=settings.AUTH_USER_MODEL, verbose_name="O'quvchi")),
            ],
            options={
                'verbose_name': 'Kursga yozilish (Ruxsat)',
                'verbose_name_plural': 'Kurslarga yozilishlar (Ruxsatlar)',
                'ordering': ['-status', 'course__order'],
                'unique_together': {('student', 'course')},
            },
        ),
        migrations.CreateModel(
            name='TopicProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('LOCKED', 'Yopiq'), ('NOT_STARTED', 'Boshlanmagan'), ('IN_PROGRESS', "O'rganilmoqda"), ('COMPLETED', 'Tugallangan')], default='NOT_STARTED', max_length=20, verbose_name="O'zlashtirish holati")),
                ('progress_percentage', models.PositiveIntegerField(default=0, verbose_name="O'zlashtirish foizi (0-100%)")),
                ('slides_viewed', models.PositiveIntegerField(default=0, verbose_name="Ko'rilgan slaydlar soni")),
                ('is_presentation_downloaded', models.BooleanField(default=False, verbose_name='PDF yuklab olinganmi')),
                ('last_accessed', models.DateTimeField(auto_now=True, verbose_name='Oxirgi kirish vaqti')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_progresses', to=settings.AUTH_USER_MODEL, verbose_name="O'quvchi")),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresses', to='courses.topic', verbose_name='Mavzu')),
            ],
            options={
                'verbose_name': "Mavzu o'zlashtirish progressi",
                'verbose_name_plural': "Mavzular o'zlashtirish progresslari",
                'unique_together': {('student', 'topic')},
            },
        ),
    ]
