# Generated by Django 6.1.1 on 2026-10-01 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name="E'lon sarlavhasi")),
                ('content', models.TextField(verbose_name="E'lon matni")),
                ('is_pinned', models.BooleanField(default=False, verbose_name="Yuqoriga qadab qo'yish")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Chop etilgan vaqti')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_announcements', to=settings.AUTH_USER_MODEL, verbose_name='Muallif')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='accounts.group', verbose_name="Qaysi guruhga (bo'sh bo'lsa hammaga)")),
            ],
            options={
                'verbose_name': "E'lon",
                'verbose_name_plural': "E'lonlar",
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('message', models.TextField(verbose_name='Xabar matni')),
                ('notification_type', models.CharField(choices=[('ASSIGNMENT', 'Vazifa xabarnomasi'), ('QUIZ', 'Test xabarnomasi'), ('ATTENDANCE', 'Davomat xabarnomasi'), ('RANKING', 'Reyting oʻzgarishi'), ('SYSTEM', 'Tizim xabari')], default='SYSTEM', max_length=30, verbose_name='Turi')),
                ('link', models.CharField(blank=True, max_length=255, verbose_name="Yo'naltiruvchi havola")),
                ('is_read', models.BooleanField(default=False, verbose_name="O'qilganmi")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan vaqti')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Qabul qiluvchi')),
            ],
            options={
                'verbose_name': 'Bildirishnoma',
                'verbose_name_plural': 'Bildirishnomalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
