# Generated by Django 6.1.1 on 2026-10-01 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Topshiriq nomi (masalan: Loyiha uchun asosiy metadasturlarni sozlash)')),
                ('description', models.TextField(verbose_name='Topshiriq sharti va talablari')),
                ('max_score', models.PositiveIntegerField(default=100, verbose_name='Maksimal ball (masalan: 100 BALL)')),
                ('deadline_text', models.CharField(default='1 kun qoldi', max_length=100, verbose_name='Muddat matni (masalan: Muddat: 1 kun qoldi)')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name="Topshirishning so'nggi muddati")),
                ('is_daily_featured', models.BooleanField(default=False, verbose_name="Bugungi bosh vazifa (Dashboard bannerida ko'rinadi)")),
                ('banner_subtitle', models.CharField(blank=True, default='Haftalik amaliy topshiriq topshirish vaqti tugashiga 1 kun qoldi.', max_length=255, verbose_name='Dashboard banner taglavhasi')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='assignments/materials/', verbose_name='Biriktirilgan manba fayli / shablon')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='courses.topic', verbose_name='Mavzu')),
            ],
            options={
                'verbose_name': 'Amaliy topshiriq (Uy ishi)',
                'verbose_name_plural': 'Amaliy topshiriqlar (Uy ishlari)',
                'ordering': ['-is_daily_featured', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='submissions/images/%Y/%m/', verbose_name='Amaliy ish skrinshoti / rasmi (Natija isboti)')),
                ('submission_file', models.FileField(blank=True, null=True, upload_to='submissions/files/%Y/%m/', verbose_name='Topshirilgan fayl (.zip, .html, .py)')),
                ('github_url', models.URLField(blank=True, null=True, verbose_name='GitHub havola')),
                ('code_text', models.TextField(blank=True, verbose_name='Topshirilgan kod yoki matn')),
                ('student_comment', models.TextField(blank=True, verbose_name="O'quvchi izohi")),
                ('status', models.CharField(choices=[('PENDING', 'Kutilmoqda (Tekshirilmagan)'), ('GRADED', 'Baholandi'), ('REJECTED', 'Qayta topshirishga qaytarildi')], default='PENDING', max_length=20, verbose_name='Holati')),
                ('score', models.PositiveIntegerField(blank=True, null=True, verbose_name="Qo'yilgan ball")),
                ('teacher_feedback', models.TextField(blank=True, verbose_name="O'qituvchi taqrizi va maslahati")),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Topshirilgan sana')),
                ('graded_at', models.DateTimeField(blank=True, null=True, verbose_name='Baholangan sana')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assignments.assignment', verbose_name='Topshiriq')),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_assignments', to=settings.AUTH_USER_MODEL, verbose_name="Baholagan o'qituvchi")),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submissions', to=settings.AUTH_USER_MODEL, verbose_name="O'quvchi")),
            ],
            options={
                'verbose_name': 'Topshirilgan vazifa',
                'verbose_name_plural': 'Topshirilgan vazifalar',
                'ordering': ['-submitted_at'],
                'unique_together': {('assignment', 'student')},
            },
        ),
    ]
