# Generated by Django 6.1.1 on 2026-10-01 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Kutilmoqda (Tekshirilmagan)'), ('APPROVED', 'Qabul qilindi va baholandi'), ('REJECTED', 'Qayta topshirishga qaytarildi')], default='PENDING', max_length=20, verbose_name='Holati'),
        ),
    ]
