# Generated by Django 6.1.1 on 2026-10-01 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AchievementBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Yutuq nishoni nomi')),
                ('description', models.TextField(verbose_name='Qanday erishiladi')),
                ('icon', models.CharField(default='award', max_length=50, verbose_name='Icon nomi')),
                ('points_required', models.PositiveIntegerField(default=100, verbose_name='Kerakli ball')),
            ],
            options={
                'verbose_name': 'Yutuq nishoni',
                'verbose_name_plural': 'Yutuq nishonlari',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Sana')),
                ('status', models.CharField(choices=[('PRESENT', 'Qatnashdi (Kelgan)'), ('ABSENT', 'Qatnashmadi (Kelmagan)'), ('EXCUSED', 'Sababli'), ('LATE', 'Kechikdi')], default='PRESENT', max_length=20, verbose_name='Davomat holati')),
                ('teacher_note', models.CharField(blank=True, max_length=255, verbose_name="O'qituvchi izohi")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='accounts.group', verbose_name='Guruh')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_attendances', to=settings.AUTH_USER_MODEL, verbose_name='Belgilagan ustoz')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL, verbose_name="O'quvchi")),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='courses.topic', verbose_name="O'tilgan dars/mavzu")),
            ],
            options={
                'verbose_name': 'Davomat qaydi',
                'verbose_name_plural': 'Davomat qaydlari',
                'ordering': ['-date', 'student__first_name'],
                'unique_together': {('student', 'date', 'group')},
            },
        ),
        migrations.CreateModel(
            name='StudentBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.achievementbadge')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "O'quvchi yutug'i",
                'verbose_name_plural': "O'quvchilar yutuqlari",
                'unique_together': {('student', 'badge')},
            },
        ),
    ]
